package com.example.espresso.util;

import com.example.espresso.model.Character;

/**
 * Created by quanlt on 10/01/2017.
 */

public class DataFactory {
    public static Character[] characters = new Character[]{
      new Character("U-WING","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("U-WING","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("SHORETROOPERS","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("SAW GERRERA","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("PAO","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("MOROFF","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("K-2SO (KAY-TUESSO)","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("JYN ERSO","Putting behind a checkered past by lending her skills to a greater cause, Jyn Erso is impetuous, defiant, and eager to bring the battle to the Empire. Used to operating alone, she finds higher purpose by taking on a desperate mission for the Rebel Alliance.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("IMPERIAL GROUND CREW","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("DIRECTOR ORSON KRENNIC","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("CHIRRUT IMWE","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("CAPTAIN CASSIAN ANDOR","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("C2-B5","A sturdy troop transport and gunship used by the Rebel Alliance, the U-wing starfighter is a well-armed swing-wing vessel that must penetrate heavy fire zones to deposit soldiers onto battlefields and then fly air support during dangerous missions against the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("BODHI ROOK","A former Imperial pilot, Bodhi has strong piloting and technical skills that he will put to use for the Rebellion. Ever practical, but highly anxious, Bodhi must gather his courage to bring the battle to the Empire.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
            new Character("BAZE MALBUS","The harsh reality of his Imperial-occupied home world has hardened Baze Malbus into a pragmatic soldier and a crack shot with his heavy repeater cannon. Baze has a bravado that provides a marked contrast to the spiritual centeredness of his best friend and moral compass, Chirrut Îmwe.","http://img.lum.dolimg.com/v1/images/u-wing_3a89a295.jpeg"),
    };
}
